### PR TITLE
Fixed bad setter behaviour on .text(), .html() and .val() (Fixes #22)

### LINKED ISSUE #22: Variable parameter methods .html(), .text() and .val() broken
JQuery implements the variable parameter methods `.html()`, `.text()` and `.val()`. These methods are getters, when no argument is supplied to the method, and setters, when an argument is supplied. Example:

```js
// getter
value = $('#myname');
console.log('The value of <input id="myname"> is ' + value);

// setter
value = "Leopoldo";
$('#myname').val(value);
console.log('The value of <input id="myname"> is now set to "Leopoldo");'
```

The getter method always returns the value while the setter method **always returns this jQuery element itself** allowing to chain multiple instructions like this:

```js
	$element = $('<textarea>', {
		'name': element.name,
		'class': 'ui-widget-content',
	}).val(element.value).appendTo($container)
```

With the current version of tinymce-jquery, this code now crashed in the case that `element.value` is not defined, since the internal check of the overridden method is not implemented correctly. Instead of checking for `arguments.length === 0`, it checks for `valueOrProducer === undefined` which is definitively wrong:

https://github.com/tinymce/tinymce-jquery/blob/f5db6e598c467a2256325899c2abe8371c3ed703/src/main/ts/Patch.ts#L376

For this reason, `.val(undefined)` is wrongly interpreted as a "getter"-call instead of a "setter"-call of `.val()`. The same applies to `.html()` and `.text()`

### PR DESCRIPTION
**Pull request by tuxpoldo**
This would fix the bad behaviour described in Issue #22

### CODE REVIEW

File: src/main/ts/Patch.ts [hunk 1]
```diff
@@ -373,29 +385,35 @@ type JQueryValProducer = (this: HTMLElement, index: number, value: JQueryValValu
...
-          if (Type.isFunction(valueOrProducer)) {
+          if (Type.isFunction(fixedValueOrProducer)) {
             // these steps are so the correct index is passed to the producer fn
             const origValue = origFn.call($(el));
-            const newValue = valueOrProducer.call(el, i, origValue ?? '');
+            const newValue = fixedValueOrProducer.call(el, i, origValue ?? '');
             (origFn as ValSetterType).call($(el), newValue);
           } else {
-            (origFn as ValSetterType).call($(elm), valueOrProducer);
+            (origFn as ValSetterType).call($(elm), fixedValueOrProducer);
```
Comment (tiny-james) [inline src/main/ts/Patch.ts:416]: This line shouldn't need to change as it is calling the original JQuery function.

File: src/main/ts/Patch.ts [hunk 2]
```diff
@@ -373,29 +385,35 @@ type JQueryValProducer = (this: HTMLElement, index: number, value: JQueryValValu
...
+      // behave like original jQuery if argument is explicitely undefined
+      const fixedValueOrProducer = (
+        valueOrProducer === undefined
+          ? ''
+          : valueOrProducer
+      );
       this.each((i, el) => {
         withTinymceInstance(el, (ed) => {
-          const val = Type.isFunction(valueOrProducer) ? valueOrProducer.call(el, i, ed.getContent()) : valueOrProducer;
+          const val = Type.isFunction(fixedValueOrProducer) ? fixedValueOrProducer.call(el, i, ed.getContent()) : fixedValueOrProducer;
```
Comment (tiny-james) [inline src/main/ts/Patch.ts:404]: The default value is only needed on this line. I would prefer you write it like this:
```suggestion
          const val = Type.isFunction(valueOrProducer) ? valueOrProducer.call(el, i, ed.getContent()) : valueOrProducer ?? '';
```

File: src/main/ts/Patch.ts [hunk 3]
```diff
@@ -373,29 +385,35 @@ type JQueryValProducer = (this: HTMLElement, index: number, value: JQueryValValu
...
-    if (valueOrProducer === undefined) {
+    if (arguments.length === 0) {
       if (this.length >= 1) {
         return withTinymceInstance(this[0], (ed) => ed.getContent(), (elm) => origFn.call($(elm)));
       }
       // when no elements exist to query simply return undefined
       return undefined;
     } else {
       type ValSetterType = (valueOrProducer: JQueryValValue | JQueryValProducer) => JQuery<HTMLElement>;
+      // behave like original jQuery if argument is explicitely undefined
```
Comment (tiny-james) [inline src/main/ts/Patch.ts:396]:
```suggestion
      // behave like original jQuery if argument is explicitly undefined
```

File: src/main/ts/Patch.ts [hunk 4]
```diff
@@ -373,29 +385,35 @@ type JQueryValProducer = (this: HTMLElement, index: number, value: JQueryValValu
...
+      const fixedValueOrProducer = (
```
Comment (tiny-james) [inline src/main/ts/Patch.ts:397]: I would just do the defaulting inline as it is only needed in one location in this function. See suggestion below.

File: src/main/ts/Patch.ts [hunk 5]
```diff
@@ -373,29 +385,35 @@ type JQueryValProducer = (this: HTMLElement, index: number, value: JQueryValValu
...
           const html = Type.isArray(val) ? val.join('') : `${val}`;
           ed.setContent(html);
         }, (elm) => {
           // work around bad type inference
-          if (Type.isFunction(valueOrProducer)) {
+          if (Type.isFunction(fixedValueOrProducer)) {
             // these steps are so the correct index is passed to the producer fn
             const origValue = origFn.call($(el));
-            const newValue = valueOrProducer.call(el, i, origValue ?? '');
+            const newValue = fixedValueOrProducer.call(el, i, origValue ?? '');
```
Comment (tiny-james) [inline src/main/ts/Patch.ts:413]: Just use the original value here. It can't be undefined here.

File: src/main/ts/Patch.ts [hunk 6]
```diff
@@ -373,29 +385,35 @@ type JQueryValProducer = (this: HTMLElement, index: number, value: JQueryValValu
...
         withTinymceInstance(el, (ed) => {
-          const val = Type.isFunction(valueOrProducer) ? valueOrProducer.call(el, i, ed.getContent()) : valueOrProducer;
+          const val = Type.isFunction(fixedValueOrProducer) ? fixedValueOrProducer.call(el, i, ed.getContent()) : fixedValueOrProducer;
           // We don't expect to be given arrays/numbers but it's in the type...
           const html = Type.isArray(val) ? val.join('') : `${val}`;
           ed.setContent(html);
         }, (elm) => {
           // work around bad type inference
-          if (Type.isFunction(valueOrProducer)) {
+          if (Type.isFunction(fixedValueOrProducer)) {
```
Comment (tiny-james) [inline src/main/ts/Patch.ts:410]: Using the original value is fine here.

File: src/main/ts/Patch.ts (hunk 1 above)
Comment (tuxpoldo) [reply src/main/ts/Patch.ts:416]: This is right. But unfortunately using TypeScript now it not possible any more to specify here `valueOrProducer` since you will get a type error:

```
src/main/ts/Patch.ts:416:52 - error TS2345: Argument of type 'JQueryValValue | JQueryValProducer | undefined' is not assignable to parameter of type 'JQueryValValue | JQueryValProducer'.
  Type 'undefined' is not assignable to type 'JQueryValValue | JQueryValProducer'.

416             (origFn as ValSetterType).call($(elm), valueOrProducer);
                                                       ~~~~~~~~~~~~~~~


Found 1 error in src/main/ts/Patch.ts:416

error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

All this `fixedXYZ-variables-zigzag was only caused by the strict type checking of the TypeScript compiler... It is not really needed from a JavaScript point of view...

Comment (tuxpoldo) [reply src/main/ts/Patch.ts:416]: Done

File: src/main/ts/Patch.ts (hunk 2 above)
Comment (tuxpoldo) [reply src/main/ts/Patch.ts:404]: Done

File: src/main/ts/Patch.ts (hunk 3 above)
Comment (tuxpoldo) [reply src/main/ts/Patch.ts:396]: Done - please see new version

File: src/main/ts/Patch.ts (hunk 5 above)
Comment (tuxpoldo) [reply src/main/ts/Patch.ts:413]: Done - please see new version

File: src/main/ts/Patch.ts (hunk 6 above)
Comment (tuxpoldo) [reply src/main/ts/Patch.ts:410]: Done - please see new version

**Comment by tuxpoldo** [comment]
OK - I think that now I've done all changes you requested. Thank you for your review!

File: src/main/ts/Patch.ts [hunk 7]
```diff
@@ -284,7 +285,7 @@ const patchJqHtml = (origFn: JQueryHtmlFn): JQueryHtmlFn =>
                 // also if jQuery handles things not listed in the types this should
                 // hopefully allow us to work gracefully...
                 const elem = document.createElement('div');
-                (origFn as HtmlSetterType).call($(elem), htmlOrNode);
+                (origFn as HtmlSetterType).call($(elem), htmlOrNode === undefined ? '' : htmlOrNode);
```
Comment (tiny-james) [inline src/main/ts/Patch.ts:288]: Since this is the original Jquery function as I understand it it does not require the default?

File: src/main/ts/Patch.ts [hunk 8]
```diff
@@ -297,7 +298,7 @@ const patchJqHtml = (origFn: JQueryHtmlFn): JQueryHtmlFn =>
             const newValue = htmlOrNodeOrProducer.call(el, i, origValue);
             (origFn as HtmlSetterType).call($(el), newValue);
           } else {
-            (origFn as HtmlSetterType).call($(elm), htmlOrNodeOrProducer);
+            (origFn as HtmlSetterType).call($(elm), htmlOrNodeOrProducer === undefined ? '' : htmlOrNodeOrProducer);
```
Comment (tiny-james) [inline src/main/ts/Patch.ts:301]:
```suggestion
            (origFn as HtmlSetterType).call($(elm), htmlOrNodeOrProducer ?? '');
```

File: src/main/ts/Patch.ts [hunk 9]
```diff
@@ -395,7 +398,7 @@ const patchJqVal = (origFn: JQueryValFn): JQueryValFn =>
             const newValue = valueOrProducer.call(el, i, origValue ?? '');
             (origFn as ValSetterType).call($(el), newValue);
           } else {
-            (origFn as ValSetterType).call($(elm), valueOrProducer);
+            (origFn as ValSetterType).call($(elm), valueOrProducer === undefined ? '' : valueOrProducer);
```
Comment (tiny-james) [inline src/main/ts/Patch.ts:401]:
```suggestion
            (origFn as ValSetterType).call($(elm), valueOrProducer ?? '');
```

**Review by tiny-james — APPROVED** [review]
Thanks for the changes. I have a query and a few minor suggestions though I don't mind if it stays as it is. 

I just realized that the CLA bot was not setup for this repo so if you haven't signed the contributor license agreement you'll need to do that before I can merge the PR.

File: src/main/ts/Patch.ts (hunk 7 above)
Comment (tuxpoldo) [reply src/main/ts/Patch.ts:288]: You **must** pass something, since you calling it as a **setter**. In JavaScript it is OK do do so:
```js
var value = undefined;
$('<textarea>').val(value);
```

Unfortunately, since this is TypeScript, you will get an error if you do not resolve `htmlOrNode` to a string.

[the remark this answers is not in the document]
Comment (tuxpoldo) [reply src/main/ts/Patch.ts]: Done

File: src/main/ts/Patch.ts (hunk 8 above)
Comment (tuxpoldo) [reply src/main/ts/Patch.ts]: Done

File: src/main/ts/Patch.ts [hunk 10]
```diff
@@ -352,7 +354,7 @@ const patchJqText = (origFn: JQueryTextFn): JQueryTextFn =>
             const newValue = valueOrProducer.call(el, i, origValue);
             (origFn as TextSetterType).call($(el), newValue);
           } else {
-            (origFn as TextSetterType).call($(elm), valueOrProducer);
+            (origFn as TextSetterType).call($(elm), valueOrProducer === undefined ? '' : valueOrProducer);
```
[the remark this answers is not in the document]
Comment (tuxpoldo) [reply src/main/ts/Patch.ts]: Done

File: src/main/ts/Patch.ts (hunk 9 above)
Comment (tuxpoldo) [reply src/main/ts/Patch.ts]: Done

**Comment by tuxpoldo** [comment]
@tiny-james - Thank you for your review. I made some changes as you requested. Unfortunately I have no idea on how to sign the CLA - I also checked my E-Mails but I found absolutely nothing about it. Can you please help?

**Review by jscasca — APPROVED** [review]
